 
import request, { GET, PATCH } from "../utilities/Fetches";
import { $replace } from "../utilities/Strings";

const BASE = "/seller-listing-settings";

const GET_SELLER_LISTING_SETTINGS = BASE + "/${id}";
const UPDATE_SELLER_LISTING_SETTINGS = BASE + "/${id}";

/**
 * @param {Object} pathVariables = {
 * 	id: String
 * }
 */
export function getSellerListingSettingsAPI(pathVariables, callback) {
	const api = $replace(GET_SELLER_LISTING_SETTINGS, pathVariables);
	request(api, GET, null, callback);
}

/**
 * 
 * @param {Object} pathVariables = {
 * 	id: String
 * }
 * @param {Object} payload = {
 * 	autoGenerateTitle: Boolean,
 *  autoGenerateDescription: Boolean,
 * 
 *  autoIncludeReturnPolicy: Boolean,
 *  autoIncludeStoreName: Boolean,
 *  autoIncludeStoreLogo: Boolean,
 * 
 *  returnPolicyText: String,
 *  storeName: String,
 *  storeLogoURL: String,
 * }
 */
export function updateSellerListingSettingsAPI(pathVariables, payload, callback) {
	const api = $replace(UPDATE_SELLER_LISTING_SETTINGS, pathVariables);
	request(api, PATCH, payload, callback);
}